module.exports = {
  ...require('./random'),
  ...require('./tools'),
  ...require('./swap'),
  ...require('./modeEncrypt'),
  main: require('./main'),
  hexnum: require('./hexnum'),
  combine4: require('./combine4'),
  bitwiseTwoNumarr: require('./bitwiseTwoNumarr'),
  decrypt: require('./decrypt'),
  extrace: require('./extrace'),
  decode: require('./decode'),
  uuid: require('./uuid'),
  numToNumarr2: require('./numToNumarr2'),
  numToNumarr4: require('./numToNumarr4'),
  numToNumarr8: require('./numToNumarr8'),
  string2ascii: require('./string2ascii'),
  ascii2string: require('./ascii2string'),
  getFixedNumber: require('./getFixedNumber'),
  numarrAddTime: require('./numarrAddTime'),
  numarrEncrypt: require('./numarrEncrypt'),
  numarr2string: require('./numarr2string'),
  numarrJoin: require('./numarrJoin'),
  dynamicExec: require('./dynamicExec'),
}

